from tgbot.misc.texts import _


back = _('Back')
skip = _('Skip')
next_ = _('Next')
cancel = _('Cancel')
choose_language = _('🌍 Choose language')
settings = _('Settings')
choose_group = _('👥 Choose group')
verification = _('Verification')
via_phone = _('Via phone')
check_phone = _('Check phone')
kai_login = _('Login to KAI')
kai_logout = _('Logout from KAI')
unlink_account = _('Unlink account')
remove_favorite = _('Remove from favorites')
add_favorite = _('Add to favorites')
channel = _('Channel')

enable_emoji = _('Enable emoji')
disable_emoji = _('Disable emoji')
enable_teachers = _('Enable teachers')
disable_teachers = _('Disable teachers')

today = _('Today')
tomorrow = _('Tomorrow')
day_after_tomorrow = _('Day after tomorrow')
week_schedule = _('Week schedule')
full_schedule = _('Full schedule')
teachers = _('Teachers')
exams = _('Exams')

even_week = _('2️⃣ Even')
odd_week = _('1️⃣ Odd')
prev_week = _('<<< Prev. week')
next_week = _('Next week >>>')
prev_day = _('< Prev. day')
next_day = _('Next day >')
group = _('Group №{group_name}')

my_group = _('My group')
classmates = _('Classmates')
edit_pinned_text = _('Edit pinned text')
homework = _('Homework')
clear = _('Clear')

documents = _('Documents')
syllabus = _('Syllabus')
educational_program = _('Educational program')
study_schedule = _('Study schedule')

contact_us = _('Contact us')
